import json
import gradio as gr
from langchain_community.vectorstores import Chroma
from langchain_community.embeddings import OllamaEmbeddings
from langchain_community.llms import Ollama
from langchain.prompts import PromptTemplate
from dotenv import load_dotenv
import os

load_dotenv()

# === Load Vector DB ===
embedding = OllamaEmbeddings(model=os.getenv("EMBEDDING_MODEL", "phi3"))
vectorstore = Chroma(
    persist_directory=os.getenv("PERSIST_DIR", "chroma_db"),
    embedding_function=embedding,
)
retriever = vectorstore.as_retriever()

# === Load all topics for dropdown ===
topics_set = set()
for doc in vectorstore.get()["metadatas"]:
    topics_set.add(doc["topic"])
topics = sorted(list(topics_set))

# === Prompt Template for Generation ===
template = """
You are a UPSC Mains question paper designer.

Given the following example questions from the topic: "{topic}", generate {num} new high-quality, original UPSC Mains-style questions from this topic.

Examples:
{examples}

Now generate {num} new questions only.
"""
prompt = PromptTemplate.from_template(template)

# === Use Ollama LLM ===
llm = Ollama(model=os.getenv("LLM_MODEL", "phi3"))

# === Gradio Function ===
def generate_upsc_questions(selected_topic, num):
    # Retrieve top-k example questions for that topic
    retriever.search_kwargs = {"k": num, "filter": {"topic": selected_topic}}
    docs = retriever.get_relevant_documents(selected_topic)

    if not docs:
        return f"❌ No questions found for topic: {selected_topic}"

    examples = [doc.page_content for doc in docs]

    example_text = "\n".join([f"{i+1}. {q}" for i, q in enumerate(examples)])

    final_prompt = prompt.format(topic=selected_topic, examples=example_text, num=num)
    response = llm.invoke(final_prompt)

    return f"### 🔄 New Questions (Generated by phi3)\n\n{response.strip()}"

# === Gradio UI ===
gr.Interface(
    fn=generate_upsc_questions,
    inputs=[
        gr.Dropdown(choices=topics, label="📘 Select UPSC Topic"),
        gr.Slider(minimum=1, maximum=10, value=5, label="🔢 Number of New Questions")
    ],
    outputs="markdown",
    title="🎓 UPSC GS Question Generator (phi3 + LangChain + Chroma)",
    description="Select a topic and generate high-quality Mains-style questions based on past patterns.",
).launch()
